Add UUID to Mushra results
audiolabs/webMUSHRA pull request #87
Opened 2022-05-16 10:28 UTC by fzalkow

In the resulting CSV file, different participants can only be distinguished by their names given in the final questionnaire. This might be error-prone because different participants could use the same name. I added a UUID to avoid this case (only implemented for MUSHRA in the PHP file).

2022-06-01 07:46 UTC, nullpunktTUD commented
Just wanted to chime in and say that this is a feature that would be extremely helpful to me, too.

Also, it looks like the most important change is actually in `Session.js`. The change in the PHP script just reflects the fact that the new data field needs to be written to the results.

Anyway, I would love to see this included for all kinds of pages.

2022-06-01 08:00 UTC, fzalkow commented
I agree that the change in the PHP file is trivial.

The main modification is including the UUID package via CDN (unpkg) in `index.html`. I do not know if using CDNs is considered acceptable in this project.

Adding this feature to other pages should be easy. One just needs to push `$session->uuid` to the corresponding results in the PHP file.

2022-07-05 17:26 UTC, faroit requested changes

2022-07-05 17:26 UTC, faroit commented on index.html
> +    <script src="https://unpkg.com/uuid@latest/dist/umd/uuidv4.min.js"></script>
can you copy in the dependency and its license?

2022-07-06 06:27 UTC, fzalkow commented
I copied the dependency and the license file. To be completely transparent: The dependency is the minified version of uuidv4 provided by the CDN unpkg. I used the license from the original repo (https://github.com/uuidjs/uuid), which does not contain the minified version. I guess the original license still applies to the minified version... I still want to mention this.

2022-07-06 06:35 UTC, faroit approved these changes
looks good.

2022-07-06 06:36 UTC, merged